### ISSUE TITLE
maybe it is not a bug,but I build failed.

### ISSUE THREAD

**Issue by huangshengsh** [OpenIdentityPlatform/OpenIDM#9]
**Describe the bug**
I git out the source code, after that,
when I try to "mvn -DskipTests -Dmaven.javadoc.skip=true clean install -f ./OpenICF/OpenDJ/forgerock-parent"  and other maven commands, I always get following errors.

Exception in thread "main" java.lang.NoClassDefFoundError: java/util/logging/Logger
        at com.google.inject.internal.util.Stopwatch.<clinit>(Stopwatch.java:27)
        at com.google.inject.internal.InternalInjectorCreator.<init>(InternalInjectorCreator.java:60)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.google.inject.Guice.createInjector(Guice.java:69)
        at com.google.inject.Guice.createInjector(Guice.java:59)
        at org.codehaus.plexus.DefaultPlexusContainer.addPlexusInjector(DefaultPlexusContainer.java:481)
        at org.codehaus.plexus.DefaultPlexusContainer.<init>(DefaultPlexusContainer.java:206)
        at org.apache.maven.cli.MavenCli.container(MavenCli.java:636)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:282)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.lang.ClassNotFoundException: java.util.logging.Logger
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        ... 18 more

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by huangshengsh** [comment]
I am using openJDK V13.0.2, maven 3.6

**Comment by huangshengsh** [comment]
I got answers，the packages should be compiled with Oracle JDK8，not openJDK V13.0.2

**Comment by maximthomas** [comment]
You can also build with Open JDK 8

**Comment by huangshengsh** [comment]
but I got many maven errors
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  19.963 s
[INFO] Finished at: 2020-03-10T14:29:47+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project openidm-util: Could not resolve dependencies for project org.forgerock.openidm:openidm-util:bundle:5.5.0-SNAPSHOT: Failure to find org.forgerock.commons:script-common:jar:3.0.3 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

**Comment by huangshengsh** [comment]
[ERROR] Failed to execute goal on project openidm-util: Could not resolve dependencies for project org.forgerock.openidm:openidm-util:bundle:5.5.0-SNAPSHOT: Could not find artifact org.forgerock.commons:script-common:jar:3.0.3 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :openidm-util

**Comment by vharseko** [comment]
https://github.com/OpenIdentityPlatform/OpenIDM/commit/c3f325788d5bf254e240a06adc581484be3467fc
